// Code generated by MockGen. DO NOT EDIT.
// Source: ../services/avatar_service.go
//
// Generated by this command:
//
//	mockgen -source=../services/avatar_service.go -destination=avatar_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/kkapel/GophProfile/internal/domain"
	services "github.com/kkapel/GophProfile/internal/services"
	storage "github.com/kkapel/GophProfile/internal/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
	isgomock struct{}
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockEventPublisher) Publish(ctx context.Context, routingKey string, event any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, routingKey, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockEventPublisherMockRecorder) Publish(ctx, routingKey, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockEventPublisher)(nil).Publish), ctx, routingKey, event)
}

// MockAvatarService is a mock of AvatarService interface.
type MockAvatarService struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarServiceMockRecorder
	isgomock struct{}
}

// MockAvatarServiceMockRecorder is the mock recorder for MockAvatarService.
type MockAvatarServiceMockRecorder struct {
	mock *MockAvatarService
}

// NewMockAvatarService creates a new mock instance.
func NewMockAvatarService(ctrl *gomock.Controller) *MockAvatarService {
	mock := &MockAvatarService{ctrl: ctrl}
	mock.recorder = &MockAvatarServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarService) EXPECT() *MockAvatarServiceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockAvatarService) Delete(ctx context.Context, id uuid.UUID, requesterID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, requesterID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAvatarServiceMockRecorder) Delete(ctx, id, requesterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAvatarService)(nil).Delete), ctx, id, requesterID)
}

// DeleteUserAvatar mocks base method.
func (m *MockAvatarService) DeleteUserAvatar(ctx context.Context, userID, requesterID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserAvatar", ctx, userID, requesterID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserAvatar indicates an expected call of DeleteUserAvatar.
func (mr *MockAvatarServiceMockRecorder) DeleteUserAvatar(ctx, userID, requesterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserAvatar", reflect.TypeOf((*MockAvatarService)(nil).DeleteUserAvatar), ctx, userID, requesterID)
}

// GetFile mocks base method.
func (m *MockAvatarService) GetFile(ctx context.Context, id uuid.UUID, size string) (*storage.Object, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFile", ctx, id, size)
	ret0, _ := ret[0].(*storage.Object)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFile indicates an expected call of GetFile.
func (mr *MockAvatarServiceMockRecorder) GetFile(ctx, id, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFile", reflect.TypeOf((*MockAvatarService)(nil).GetFile), ctx, id, size)
}

// GetMetadata mocks base method.
func (m *MockAvatarService) GetMetadata(ctx context.Context, id uuid.UUID) (domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadata", ctx, id)
	ret0, _ := ret[0].(domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetadata indicates an expected call of GetMetadata.
func (mr *MockAvatarServiceMockRecorder) GetMetadata(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadata", reflect.TypeOf((*MockAvatarService)(nil).GetMetadata), ctx, id)
}

// GetUserFile mocks base method.
func (m *MockAvatarService) GetUserFile(ctx context.Context, userID, size string) (*storage.Object, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserFile", ctx, userID, size)
	ret0, _ := ret[0].(*storage.Object)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserFile indicates an expected call of GetUserFile.
func (mr *MockAvatarServiceMockRecorder) GetUserFile(ctx, userID, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserFile", reflect.TypeOf((*MockAvatarService)(nil).GetUserFile), ctx, userID, size)
}

// List mocks base method.
func (m *MockAvatarService) List(ctx context.Context, userID string) ([]domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID)
	ret0, _ := ret[0].([]domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAvatarServiceMockRecorder) List(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAvatarService)(nil).List), ctx, userID)
}

// Upload mocks base method.
func (m *MockAvatarService) Upload(ctx context.Context, in services.UploadInput) (domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, in)
	ret0, _ := ret[0].(domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockAvatarServiceMockRecorder) Upload(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockAvatarService)(nil).Upload), ctx, in)
}
