version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - errorlint
    - gosec
    - misspell
    - revive
    - unconvert
  settings:
    revive:
      rules:
        - name: exported
  exclusions:
    rules:
      - path: \.gen\.go$
        linters:
          - revive
      - path: \.pb\.go$
        linters:
          - revive
formatters:
  enable:
    - gofmt          