// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: avatars.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createAvatar = `-- name: CreateAvatar :one
INSERT INTO avatars (
    id, user_id, file_name, mime_type, size_bytes, s3_key, upload_status, processing_status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, user_id, file_name, mime_type, size_bytes, width, height,
          s3_key, thumbnail_s3_keys, upload_status, processing_status,
          created_at, updated_at, deleted_at
`

type CreateAvatarParams struct {
	ID               uuid.UUID `json:"id"`
	UserID           string    `json:"user_id"`
	FileName         string    `json:"file_name"`
	MimeType         string    `json:"mime_type"`
	SizeBytes        int64     `json:"size_bytes"`
	S3Key            string    `json:"s3_key"`
	UploadStatus     string    `json:"upload_status"`
	ProcessingStatus string    `json:"processing_status"`
}

func (q *Queries) CreateAvatar(ctx context.Context, arg CreateAvatarParams) (Avatar, error) {
	row := q.db.QueryRow(ctx, createAvatar,
		arg.ID,
		arg.UserID,
		arg.FileName,
		arg.MimeType,
		arg.SizeBytes,
		arg.S3Key,
		arg.UploadStatus,
		arg.ProcessingStatus,
	)
	var i Avatar
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileName,
		&i.MimeType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.S3Key,
		&i.ThumbnailS3Keys,
		&i.UploadStatus,
		&i.ProcessingStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAvatarByID = `-- name: GetAvatarByID :one
SELECT id, user_id, file_name, mime_type, size_bytes, width, height,
       s3_key, thumbnail_s3_keys, upload_status, processing_status,
       created_at, updated_at, deleted_at
FROM avatars
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAvatarByID(ctx context.Context, id uuid.UUID) (Avatar, error) {
	row := q.db.QueryRow(ctx, getAvatarByID, id)
	var i Avatar
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileName,
		&i.MimeType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.S3Key,
		&i.ThumbnailS3Keys,
		&i.UploadStatus,
		&i.ProcessingStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLatestAvatarByUserID = `-- name: GetLatestAvatarByUserID :one
SELECT id, user_id, file_name, mime_type, size_bytes, width, height,
       s3_key, thumbnail_s3_keys, upload_status, processing_status,
       created_at, updated_at, deleted_at
FROM avatars
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestAvatarByUserID(ctx context.Context, userID string) (Avatar, error) {
	row := q.db.QueryRow(ctx, getLatestAvatarByUserID, userID)
	var i Avatar
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileName,
		&i.MimeType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.S3Key,
		&i.ThumbnailS3Keys,
		&i.UploadStatus,
		&i.ProcessingStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAvatarsByUserID = `-- name: ListAvatarsByUserID :many
SELECT id, user_id, file_name, mime_type, size_bytes, width, height,
       s3_key, thumbnail_s3_keys, upload_status, processing_status,
       created_at, updated_at, deleted_at
FROM avatars
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAvatarsByUserID(ctx context.Context, userID string) ([]Avatar, error) {
	rows, err := q.db.Query(ctx, listAvatarsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Avatar{}
	for rows.Next() {
		var i Avatar
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FileName,
			&i.MimeType,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
			&i.S3Key,
			&i.ThumbnailS3Keys,
			&i.UploadStatus,
			&i.ProcessingStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAvatar = `-- name: SoftDeleteAvatar :one
UPDATE avatars
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, file_name, mime_type, size_bytes, width, height,
          s3_key, thumbnail_s3_keys, upload_status, processing_status,
          created_at, updated_at, deleted_at
`

func (q *Queries) SoftDeleteAvatar(ctx context.Context, id uuid.UUID) (Avatar, error) {
	row := q.db.QueryRow(ctx, softDeleteAvatar, id)
	var i Avatar
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileName,
		&i.MimeType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.S3Key,
		&i.ThumbnailS3Keys,
		&i.UploadStatus,
		&i.ProcessingStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateProcessingResult = `-- name: UpdateProcessingResult :one
UPDATE avatars
SET processing_status = $2,
    thumbnail_s3_keys = $3,
    width = $4,
    height = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, file_name, mime_type, size_bytes, width, height,
          s3_key, thumbnail_s3_keys, upload_status, processing_status,
          created_at, updated_at, deleted_at
`

type UpdateProcessingResultParams struct {
	ID               uuid.UUID `json:"id"`
	ProcessingStatus string    `json:"processing_status"`
	ThumbnailS3Keys  []byte    `json:"thumbnail_s3_keys"`
	Width            *int32    `json:"width"`
	Height           *int32    `json:"height"`
}

func (q *Queries) UpdateProcessingResult(ctx context.Context, arg UpdateProcessingResultParams) (Avatar, error) {
	row := q.db.QueryRow(ctx, updateProcessingResult,
		arg.ID,
		arg.ProcessingStatus,
		arg.ThumbnailS3Keys,
		arg.Width,
		arg.Height,
	)
	var i Avatar
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileName,
		&i.MimeType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.S3Key,
		&i.ThumbnailS3Keys,
		&i.UploadStatus,
		&i.ProcessingStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateProcessingStatus = `-- name: UpdateProcessingStatus :exec
UPDATE avatars
SET processing_status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateProcessingStatusParams struct {
	ID               uuid.UUID `json:"id"`
	ProcessingStatus string    `json:"processing_status"`
}

func (q *Queries) UpdateProcessingStatus(ctx context.Context, arg UpdateProcessingStatusParams) error {
	_, err := q.db.Exec(ctx, updateProcessingStatus, arg.ID, arg.ProcessingStatus)
	return err
}

const updateUploadStatus = `-- name: UpdateUploadStatus :exec
UPDATE avatars
SET upload_status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUploadStatusParams struct {
	ID           uuid.UUID `json:"id"`
	UploadStatus string    `json:"upload_status"`
}

func (q *Queries) UpdateUploadStatus(ctx context.Context, arg UpdateUploadStatusParams) error {
	_, err := q.db.Exec(ctx, updateUploadStatus, arg.ID, arg.UploadStatus)
	return err
}
