// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const isEventProcessed = `-- name: IsEventProcessed :one
SELECT EXISTS (
    SELECT 1 FROM processed_events WHERE event_id = $1
)
`

func (q *Queries) IsEventProcessed(ctx context.Context, eventID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isEventProcessed, eventID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const markEventProcessed = `-- name: MarkEventProcessed :exec
INSERT INTO processed_events (event_id, event_type)
VALUES ($1, $2)
ON CONFLICT (event_id) DO NOTHING
`

type MarkEventProcessedParams struct {
	EventID   uuid.UUID `json:"event_id"`
	EventType string    `json:"event_type"`
}

func (q *Queries) MarkEventProcessed(ctx context.Context, arg MarkEventProcessedParams) error {
	_, err := q.db.Exec(ctx, markEventProcessed, arg.EventID, arg.EventType)
	return err
}
