// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Avatar struct {
	ID               uuid.UUID  `json:"id"`
	UserID           string     `json:"user_id"`
	FileName         string     `json:"file_name"`
	MimeType         string     `json:"mime_type"`
	SizeBytes        int64      `json:"size_bytes"`
	Width            *int32     `json:"width"`
	Height           *int32     `json:"height"`
	S3Key            string     `json:"s3_key"`
	ThumbnailS3Keys  []byte     `json:"thumbnail_s3_keys"`
	UploadStatus     string     `json:"upload_status"`
	ProcessingStatus string     `json:"processing_status"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
	DeletedAt        *time.Time `json:"deleted_at"`
}
