// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AvatarStatus.
const (
	Completed  AvatarStatus = "completed"
	Failed     AvatarStatus = "failed"
	Processing AvatarStatus = "processing"
)

// Valid indicates whether the value is a known member of the AvatarStatus enum.
func (e AvatarStatus) Valid() bool {
	switch e {
	case Completed:
		return true
	case Failed:
		return true
	case Processing:
		return true
	default:
		return false
	}
}

// Defines values for SizeQuery.
const (
	SizeQueryN100x100 SizeQuery = "100x100"
	SizeQueryN300x300 SizeQuery = "300x300"
	SizeQueryOriginal SizeQuery = "original"
)

// Valid indicates whether the value is a known member of the SizeQuery enum.
func (e SizeQuery) Valid() bool {
	switch e {
	case SizeQueryN100x100:
		return true
	case SizeQueryN300x300:
		return true
	case SizeQueryOriginal:
		return true
	default:
		return false
	}
}

// Defines values for GetAvatarParamsSize.
const (
	GetAvatarParamsSizeN100x100 GetAvatarParamsSize = "100x100"
	GetAvatarParamsSizeN300x300 GetAvatarParamsSize = "300x300"
	GetAvatarParamsSizeOriginal GetAvatarParamsSize = "original"
)

// Valid indicates whether the value is a known member of the GetAvatarParamsSize enum.
func (e GetAvatarParamsSize) Valid() bool {
	switch e {
	case GetAvatarParamsSizeN100x100:
		return true
	case GetAvatarParamsSizeN300x300:
		return true
	case GetAvatarParamsSizeOriginal:
		return true
	default:
		return false
	}
}

// Defines values for GetUserAvatarParamsSize.
const (
	GetUserAvatarParamsSizeN100x100 GetUserAvatarParamsSize = "100x100"
	GetUserAvatarParamsSizeN300x300 GetUserAvatarParamsSize = "300x300"
	GetUserAvatarParamsSizeOriginal GetUserAvatarParamsSize = "original"
)

// Valid indicates whether the value is a known member of the GetUserAvatarParamsSize enum.
func (e GetUserAvatarParamsSize) Valid() bool {
	switch e {
	case GetUserAvatarParamsSizeN100x100:
		return true
	case GetUserAvatarParamsSizeN300x300:
		return true
	case GetUserAvatarParamsSizeOriginal:
		return true
	default:
		return false
	}
}

// Avatar defines model for Avatar.
type Avatar struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Status    AvatarStatus       `json:"status"`

	// Url Ссылка на файл аватарки
	Url    string `json:"url"`
	UserId string `json:"user_id"`
}

// AvatarStatus defines model for Avatar.Status.
type AvatarStatus string

// AvatarMetadata defines model for AvatarMetadata.
type AvatarMetadata struct {
	CreatedAt  time.Time          `json:"created_at"`
	Dimensions *Dimensions        `json:"dimensions,omitempty"`
	FileName   string             `json:"file_name"`
	Id         openapi_types.UUID `json:"id"`
	MimeType   string             `json:"mime_type"`
	Size       int64              `json:"size"`
	Thumbnails *[]Thumbnail       `json:"thumbnails,omitempty"`
	UpdatedAt  time.Time          `json:"updated_at"`
	UserId     string             `json:"user_id"`
}

// Dimensions defines model for Dimensions.
type Dimensions struct {
	Height int `json:"height"`
	Width  int `json:"width"`
}

// Error defines model for Error.
type Error struct {
	Details *string `json:"details,omitempty"`
	Error   string  `json:"error"`

	// MaxSize Максимальный размер файла в байтах (для ответа 413)
	MaxSize *int64 `json:"max_size,omitempty"`
}

// Thumbnail defines model for Thumbnail.
type Thumbnail struct {
	// Size Example: 100x100
	Size string `json:"size"`
	Url  string `json:"url"`
}

// AvatarID defines model for AvatarID.
type AvatarID = openapi_types.UUID

// SizeQuery defines model for SizeQuery.
type SizeQuery string

// UserID defines model for UserID.
type UserID = string

// UserIDHeader defines model for UserIDHeader.
type UserIDHeader = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// InternalError defines model for InternalError.
type InternalError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// PayloadTooLarge defines model for PayloadTooLarge.
type PayloadTooLarge = Error

// UploadAvatarMultipartBody defines parameters for UploadAvatar.
type UploadAvatarMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// UploadAvatarParams defines parameters for UploadAvatar.
type UploadAvatarParams struct {
	// XUserID Идентификатор пользователя, выполняющего запрос
	XUserID UserIDHeader `json:"X-User-ID"`
}

// DeleteAvatarParams defines parameters for DeleteAvatar.
type DeleteAvatarParams struct {
	// XUserID Идентификатор пользователя, выполняющего запрос
	XUserID UserIDHeader `json:"X-User-ID"`
}

// GetAvatarParams defines parameters for GetAvatar.
type GetAvatarParams struct {
	// Size Требуемый размер изображения
	Size *GetAvatarParamsSize `form:"size,omitempty" json:"size,omitempty"`
}

// GetAvatarParamsSize defines parameters for GetAvatar.
type GetAvatarParamsSize string

// DeleteUserAvatarParams defines parameters for DeleteUserAvatar.
type DeleteUserAvatarParams struct {
	// XUserID Идентификатор пользователя, выполняющего запрос
	XUserID UserIDHeader `json:"X-User-ID"`
}

// GetUserAvatarParams defines parameters for GetUserAvatar.
type GetUserAvatarParams struct {
	// Size Требуемый размер изображения
	Size *GetUserAvatarParamsSize `form:"size,omitempty" json:"size,omitempty"`
}

// GetUserAvatarParamsSize defines parameters for GetUserAvatar.
type GetUserAvatarParamsSize string

// UploadAvatarMultipartRequestBody defines body for UploadAvatar for multipart/form-data ContentType.
type UploadAvatarMultipartRequestBody UploadAvatarMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// UploadAvatar Загрузка аватарки
	// (POST /avatars)
	UploadAvatar(w http.ResponseWriter, r *http.Request, params UploadAvatarParams)
	// DeleteAvatar Удаление аватарки
	// (DELETE /avatars/{avatar_id})
	DeleteAvatar(w http.ResponseWriter, r *http.Request, avatarId AvatarID, params DeleteAvatarParams)
	// GetAvatar Получение файла аватарки
	// (GET /avatars/{avatar_id})
	GetAvatar(w http.ResponseWriter, r *http.Request, avatarId AvatarID, params GetAvatarParams)
	// GetAvatarMetadata Получение метаданных аватарки
	// (GET /avatars/{avatar_id}/metadata)
	GetAvatarMetadata(w http.ResponseWriter, r *http.Request, avatarId AvatarID)
	// DeleteUserAvatar Удаление текущей аватарки пользователя
	// (DELETE /users/{user_id}/avatar)
	DeleteUserAvatar(w http.ResponseWriter, r *http.Request, userId UserID, params DeleteUserAvatarParams)
	// GetUserAvatar Получение текущей аватарки пользователя
	// (GET /users/{user_id}/avatar)
	GetUserAvatar(w http.ResponseWriter, r *http.Request, userId UserID, params GetUserAvatarParams)
	// ListUserAvatars Список аватарок пользователя
	// (GET /users/{user_id}/avatars)
	ListUserAvatars(w http.ResponseWriter, r *http.Request, userId UserID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// UploadAvatar Загрузка аватарки
// (POST /avatars)
func (_ Unimplemented) UploadAvatar(w http.ResponseWriter, r *http.Request, params UploadAvatarParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteAvatar Удаление аватарки
// (DELETE /avatars/{avatar_id})
func (_ Unimplemented) DeleteAvatar(w http.ResponseWriter, r *http.Request, avatarId AvatarID, params DeleteAvatarParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetAvatar Получение файла аватарки
// (GET /avatars/{avatar_id})
func (_ Unimplemented) GetAvatar(w http.ResponseWriter, r *http.Request, avatarId AvatarID, params GetAvatarParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetAvatarMetadata Получение метаданных аватарки
// (GET /avatars/{avatar_id}/metadata)
func (_ Unimplemented) GetAvatarMetadata(w http.ResponseWriter, r *http.Request, avatarId AvatarID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteUserAvatar Удаление текущей аватарки пользователя
// (DELETE /users/{user_id}/avatar)
func (_ Unimplemented) DeleteUserAvatar(w http.ResponseWriter, r *http.Request, userId UserID, params DeleteUserAvatarParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetUserAvatar Получение текущей аватарки пользователя
// (GET /users/{user_id}/avatar)
func (_ Unimplemented) GetUserAvatar(w http.ResponseWriter, r *http.Request, userId UserID, params GetUserAvatarParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListUserAvatars Список аватарок пользователя
// (GET /users/{user_id}/avatars)
func (_ Unimplemented) ListUserAvatars(w http.ResponseWriter, r *http.Request, userId UserID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// UploadAvatar operation middleware
func (siw *ServerInterfaceWrapper) UploadAvatar(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params UploadAvatarParams

	headers := r.Header

	// ------------- Required header parameter "X-User-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-ID")]; found {
		var XUserID UserIDHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-ID", valueList[0], &XUserID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-ID", Err: err})
			return
		}

		params.XUserID = XUserID

	} else {
		err := fmt.Errorf("Header parameter X-User-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadAvatar(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAvatar operation middleware
func (siw *ServerInterfaceWrapper) DeleteAvatar(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "avatar_id" -------------
	var avatarId AvatarID

	err = runtime.BindStyledParameterWithOptions("simple", "avatar_id", chi.URLParam(r, "avatar_id"), &avatarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "avatar_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteAvatarParams

	headers := r.Header

	// ------------- Required header parameter "X-User-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-ID")]; found {
		var XUserID UserIDHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-ID", valueList[0], &XUserID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-ID", Err: err})
			return
		}

		params.XUserID = XUserID

	} else {
		err := fmt.Errorf("Header parameter X-User-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAvatar(w, r, avatarId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAvatar operation middleware
func (siw *ServerInterfaceWrapper) GetAvatar(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "avatar_id" -------------
	var avatarId AvatarID

	err = runtime.BindStyledParameterWithOptions("simple", "avatar_id", chi.URLParam(r, "avatar_id"), &avatarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "avatar_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAvatarParams

	// ------------- Optional query parameter "size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "size", r.URL.Query(), &params.Size, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "size", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAvatar(w, r, avatarId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAvatarMetadata operation middleware
func (siw *ServerInterfaceWrapper) GetAvatarMetadata(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "avatar_id" -------------
	var avatarId AvatarID

	err = runtime.BindStyledParameterWithOptions("simple", "avatar_id", chi.URLParam(r, "avatar_id"), &avatarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "avatar_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAvatarMetadata(w, r, avatarId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteUserAvatar operation middleware
func (siw *ServerInterfaceWrapper) DeleteUserAvatar(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "user_id" -------------
	var userId UserID

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteUserAvatarParams

	headers := r.Header

	// ------------- Required header parameter "X-User-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-ID")]; found {
		var XUserID UserIDHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-ID", valueList[0], &XUserID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-ID", Err: err})
			return
		}

		params.XUserID = XUserID

	} else {
		err := fmt.Errorf("Header parameter X-User-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUserAvatar(w, r, userId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserAvatar operation middleware
func (siw *ServerInterfaceWrapper) GetUserAvatar(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "user_id" -------------
	var userId UserID

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserAvatarParams

	// ------------- Optional query parameter "size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "size", r.URL.Query(), &params.Size, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "size", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserAvatar(w, r, userId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUserAvatars operation middleware
func (siw *ServerInterfaceWrapper) ListUserAvatars(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "user_id" -------------
	var userId UserID

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUserAvatars(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/avatars", wrapper.UploadAvatar)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/avatars/{avatar_id}", wrapper.DeleteAvatar)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/avatars/{avatar_id}", wrapper.GetAvatar)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/avatars/{avatar_id}/metadata", wrapper.GetAvatarMetadata)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/users/{user_id}/avatar", wrapper.DeleteUserAvatar)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{user_id}/avatar", wrapper.GetUserAvatar)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{user_id}/avatars", wrapper.ListUserAvatars)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FldTxtHF/4rq3nfi1ZasCm0F75LQpIipVXaJlKlCKHBO9gTeT8yO0sgyBLYiZIoVdNUldqLVG3a/gBD",
	"cDEmNn/hzD+qzozXu2svmK/SXERCyOudj/PxnOc8M94gZd8NfI95MiSlDRJQQV0mmdBPV1appGJhHj87",
	"LCwLHkjue6RE4BfYhTb0VAM66jF0oAst1YC+2rSgBTv6oaU2oQsdYhOOUwIqq8QmHnUZKRGql17iDrGJ",
	"YA8iLphDSlJEzCZhucpcipuu+MKlkpRIFOmRcj3AyaEU3KuQet0m3/BH7KuIifUcG/9Qm9CGbdWENrxT",
	"L2DfUpvQgj14B200tAN70Idt/eXf6A101MvY3Ad60aG9IX/ESNo0h63QqIa2+YJXuEdrxCbMi1xSukdm",
	"isW1mWKR2GS2WFyb1Z+Gwxbz/LgbslMH+hD6cKC+016YkLfhIPEgG/AoZBPDfZRZnzPqMHEhxtkW7KgX",
	"5i301Ev1vXoObXgLfQv2oAWHahP6aiv2oWp2Hnrx7RRaNLUwfyo/6jg4DHwvZBrXV6nzNXsQsVDiU9n3",
	"JPP0RxoENV6m6F7hfog+bqSW/b9gK6RE/ldIaqZg3oaF60L4wmw1EqNfoQ1djIlGY1c1oKexmHG3bpMb",
	"vljmjsO8S7DpJ9xUNVQTDhM72uq5egU9tGXBk0x4tGZW+Pft+RF6qqkaOkI9DYuXFvTVM+jANoLKUltY",
	"srCj/7fQxC99ecOPPOcSrPsd2mpLNdWm2rKgB23814J9g3205TZdr/nUueP7t6iosEsw6S9twIFlEocl",
	"pZ5BC9qqYcEu9OFQNTHB0MkhPl3Ygy0SltfsL/yACclNlZQFo5I5S1RmqNihkk1J7rJxPrYJd05A2zYJ",
	"JZWR3iRmzED4ZRaG+N7WPanGJMO5K5TXmJNDmjaJRC2Hk96oLfUCDjRsMFGWehwHa7wzja85oMlcNkwY",
	"5x7RjiWkirYM/bLTsUss95fvs7LEXUzIv2CSOlTSiwm9w13mhdz3wkmwmk9G1m2ywmtsydDrxpkT6nKX",
	"LZlvcxbRzTO9DPfkZ3PJOtyTrMIEDpXVyF32KK9pL7hk7kR37sRT9HyzIhWCrut8Bs6pI3lWDCSRTAfE",
	"jrVDKqkZu/IAMp9JZhYcVcYrVZmyLhW+h9yR1bxXI5abcXa8Vp4JQ+7P7u4wGWdnLHAsnjKOD7q2FKNg",
	"pF5fQwu6agupClpaMvTGtVpcw1jTOxZs45Mu5CfWR7CLwgL7RUM3iAa0rLmZ2Y8xI5MANxIW40BeNBKQ",
	"jUUk9outUaQtUkrJv6M463hcDQCDY8dtwcHcW/HzqG/QJDvYqLCtv1Wbqgl7SHa2NdS62zpUXehY+Idy",
	"bBda6ik+pBmyD90jZBy0YX8aveNS+3vTD6q3hY/4twy1hdaV2wvEJqtMhMa4menidBEj4AfMowEnJTI7",
	"XZyeJbYWqjqSBXMqMJj3jTrDSOveueCQErkbYKMddCw7c1y5l88SyZBCRszWF03MWSiv+s76SM92o5rk",
	"ARWygBCailk6adtZCKDnGX5Z5h7Vx4fjE63n5ac4q25HFewnxZkLUxmDaObJjB8yDbNl5EZHC7TGoBRH",
	"QKWamOO5YvGoXYduFFIqHKfMzE6eMiq06jb59CRbZfWs1j+R62KGSgR+zhRKK1cm0AoijMT4XMQlYrQW",
	"NoaH2bopStQu49id19+fEbvDo3jdPgvOM9CZy6GO0UyrJpKCLvWeEdxzxRMkKDnE6Blzk2cMdfyF5PLP",
	"lNUdVOonyaVNKiyHa24yeQnJSi4wcjJVHCly7tIKK9wPWCVb3ifhHTM38M489SFbDk47d5xSXiF/6HRg",
	"m29bOmG9+OGoKxlzD6Cjco2Wq2zqmu9J4dey9oxbfv0OrRw/pv7fAPU33Veb6ukQqmmJcw4GKripU8Xx",
	"uB6eP86O78mQPW9fGhqZB6bXRu5lMTQavPclwVrKZqxVT06eajxmhIWNwWmjPkj95H6DzeBceulDxzlV",
	"x9EKuaua+lpzfyy/x93axonXqT62L11KUj90psmd6b1pHheHuqPJJjyypdziYQqT4ZlBed52cqL7ovi8",
	"M3pZlAOJN3CIh2lzFB45G19MKo/b4VRZw2WZWI0Dru8ZSIEGvLA6owM7mLGR/QUu1EyQ+o0oJPXF+j8B",
	"AAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
