apiVersion: v1
kind: ConfigMap
metadata:
  name: gophprofile-config
  namespace: gophprofile
data:
  GOPHPROFILE_HTTP_ADDRESS: ":8080"
  GOPHPROFILE_METRICS_ADDRESS: ":8081"
  GOPHPROFILE_LOGGER_LEVEL: "INFO"
  GOPHPROFILE_MIGRATIONS_PATH: "migrations"
  GOPHPROFILE_MINIO_ENDPOINT: "minio:9000"
  GOPHPROFILE_MINIO_BUCKET: "avatars"
  GOPHPROFILE_MINIO_USE_SSL: "false"
  GOPHPROFILE_TRACE_SAMPLE_RATIO: "1.0"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
  OTEL_EXPORTER_OTLP_INSECURE: "true"
  OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=development"