apiVersion: v1
kind: Secret
metadata:
  name: gophprofile-secrets
  namespace: gophprofile
type: Opaque
stringData:
  GOPHPROFILE_DATABASE_URL: "postgres://gophprofile:gophprofile@postgres:5432/gophprofile?sslmode=disable"
  GOPHPROFILE_MINIO_ACCESS_KEY: "minioadmin"
  GOPHPROFILE_MINIO_SECRET_KEY: "minioadmin"
  GOPHPROFILE_RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"