// Code generated by MockGen. DO NOT EDIT.
// Source: worker.go
//
// Generated by this command:
//
//	mockgen -source=worker.go -destination=mocks_test.go -package=worker
//

// Package worker is a generated GoMock package.
package worker

import (
	context "context"
	io "io"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/kkapel/GophProfile/internal/domain"
	storage "github.com/kkapel/GophProfile/internal/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockAvatarRepository is a mock of AvatarRepository interface.
type MockAvatarRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarRepositoryMockRecorder
	isgomock struct{}
}

// MockAvatarRepositoryMockRecorder is the mock recorder for MockAvatarRepository.
type MockAvatarRepositoryMockRecorder struct {
	mock *MockAvatarRepository
}

// NewMockAvatarRepository creates a new mock instance.
func NewMockAvatarRepository(ctrl *gomock.Controller) *MockAvatarRepository {
	mock := &MockAvatarRepository{ctrl: ctrl}
	mock.recorder = &MockAvatarRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarRepository) EXPECT() *MockAvatarRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockAvatarRepository) GetByID(ctx context.Context, id uuid.UUID) (domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAvatarRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAvatarRepository)(nil).GetByID), ctx, id)
}

// IsEventProcessed mocks base method.
func (m *MockAvatarRepository) IsEventProcessed(ctx context.Context, eventID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEventProcessed", ctx, eventID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsEventProcessed indicates an expected call of IsEventProcessed.
func (mr *MockAvatarRepositoryMockRecorder) IsEventProcessed(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEventProcessed", reflect.TypeOf((*MockAvatarRepository)(nil).IsEventProcessed), ctx, eventID)
}

// MarkEventProcessed mocks base method.
func (m *MockAvatarRepository) MarkEventProcessed(ctx context.Context, eventID uuid.UUID, eventType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkEventProcessed", ctx, eventID, eventType)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkEventProcessed indicates an expected call of MarkEventProcessed.
func (mr *MockAvatarRepositoryMockRecorder) MarkEventProcessed(ctx, eventID, eventType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkEventProcessed", reflect.TypeOf((*MockAvatarRepository)(nil).MarkEventProcessed), ctx, eventID, eventType)
}

// UpdateProcessingResult mocks base method.
func (m *MockAvatarRepository) UpdateProcessingResult(ctx context.Context, id uuid.UUID, status string, thumbnails map[string]string, width, height int32) (domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProcessingResult", ctx, id, status, thumbnails, width, height)
	ret0, _ := ret[0].(domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProcessingResult indicates an expected call of UpdateProcessingResult.
func (mr *MockAvatarRepositoryMockRecorder) UpdateProcessingResult(ctx, id, status, thumbnails, width, height any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProcessingResult", reflect.TypeOf((*MockAvatarRepository)(nil).UpdateProcessingResult), ctx, id, status, thumbnails, width, height)
}

// UpdateProcessingStatus mocks base method.
func (m *MockAvatarRepository) UpdateProcessingStatus(ctx context.Context, id uuid.UUID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProcessingStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProcessingStatus indicates an expected call of UpdateProcessingStatus.
func (mr *MockAvatarRepositoryMockRecorder) UpdateProcessingStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProcessingStatus", reflect.TypeOf((*MockAvatarRepository)(nil).UpdateProcessingStatus), ctx, id, status)
}

// MockFileStorage is a mock of FileStorage interface.
type MockFileStorage struct {
	ctrl     *gomock.Controller
	recorder *MockFileStorageMockRecorder
	isgomock struct{}
}

// MockFileStorageMockRecorder is the mock recorder for MockFileStorage.
type MockFileStorageMockRecorder struct {
	mock *MockFileStorage
}

// NewMockFileStorage creates a new mock instance.
func NewMockFileStorage(ctrl *gomock.Controller) *MockFileStorage {
	mock := &MockFileStorage{ctrl: ctrl}
	mock.recorder = &MockFileStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileStorage) EXPECT() *MockFileStorageMockRecorder {
	return m.recorder
}

// DeleteMany mocks base method.
func (m *MockFileStorage) DeleteMany(ctx context.Context, keys []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMany", ctx, keys)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMany indicates an expected call of DeleteMany.
func (mr *MockFileStorageMockRecorder) DeleteMany(ctx, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMany", reflect.TypeOf((*MockFileStorage)(nil).DeleteMany), ctx, keys)
}

// Download mocks base method.
func (m *MockFileStorage) Download(ctx context.Context, key string) (*storage.Object, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", ctx, key)
	ret0, _ := ret[0].(*storage.Object)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Download indicates an expected call of Download.
func (mr *MockFileStorageMockRecorder) Download(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockFileStorage)(nil).Download), ctx, key)
}

// Upload mocks base method.
func (m *MockFileStorage) Upload(ctx context.Context, key string, r io.Reader, size int64, contentType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, key, r, size, contentType)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upload indicates an expected call of Upload.
func (mr *MockFileStorageMockRecorder) Upload(ctx, key, r, size, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockFileStorage)(nil).Upload), ctx, key, r, size, contentType)
}
