apiVersion: v1
kind: Secret
metadata:
  name: dependencies-credentials
  namespace: gophprofile
type: Opaque
stringData:
  postgres-user: gophprofile
  postgres-password: gophprofile
  postgres-db: gophprofile
  minio-root-user: minioadmin
  minio-root-password: minioadmin
  rabbitmq-user: guest
  rabbitmq-password: guest