{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gophprofile.serviceAccountName" . }}
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
# Приложение не обращается к API Kubernetes, токен ему не нужен.
automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
{{- end }}