alertmanager:
  enabled: false

grafana:
  enabled: true
  adminPassword: admin
  service:
    type: ClusterIP

prometheus:
  prometheusSpec:
    retention: 6h
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "1Gi"